apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-premium
  namespace: leetcode-judge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-premium
  template:
    metadata:
      labels:
        app: worker-premium
    spec:
      containers:
      - name: worker-premium
        image: leetcode-worker:v1.0
        imagePullPolicy: Never

        env:
        - name: REDIS_ADDR
          value: "redis-svc:6379"
        - name: STREAM_NAME
          value: "premium-stream"
        - name: GROUP_NAME
          value: "workers-premium"
        - name: WORKER_TIER
          value: "premium"
        - name: POSTGRES_DSN
          value: "user=postgres password=postgres host=postgres dbname=leetcode sslmode=disable"


        resources: 
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "100m"
